### ISSUE TITLE
无响应

### ISSUE THREAD

**Issue by dunkirk-4** [MeetWq/nonebot-plugin-emojimix#1]
## 系统

OS: Ubuntu 21.10 x86_64 
Kernel: 5.13.0-35-generic 

## Python版本

Python 3.9.7

## nonebot版本

2.0.0b2

## go-cq端

![go-cq图](http://i0.hdslb.com/bfs/album/83a4845613cf6ea693f3ff283e60f9cd6cc11f73.png)

## nonebot端

![nonebot图](http://i0.hdslb.com/bfs/album/b724e462d2a7b9b70c851ff2ddcd447a4ad04296.png)

除此之外没有其他响应，在

```python
@emojimix.handle()
async def _(msg: dict = RegexDict()):
```
下面加了一行改成
```python
@emojimix.handle()
async def _(msg: dict = RegexDict()):
    print(msg)
```
也没有输出

**Comment by MeetWq** [comment]
用法是 emoji + emoji，如：
> 😁+😎
